### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by wickedsp1d3r** [srod/node-minify#1070]
I have a script in my `package.json`:

```
ng build --prod && npx node-minify --silence --compressor jsonminify --input ./json/*.json --output ./json/$1.min.json --option {\"replaceInPlace\":true}
```
An error this command produces looks like this:

```
Error: ENOENT: no such file or directory, open '<path>\json\$1.min.json'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:162:14
    at FSReqCallback.oncomplete (fs.js:163:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '<path>\\json\\$1.min.json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I am on Windows 10, latest Yarn. I run this on VS Code.

**Comment by srod** [comment]
Fixed in 6.0.0.
You should use that command:
```
npx node-minify --silence --compressor jsonminify --input './json/*.json' --output './json/$1.min.json' --option {\"replaceInPlace\":true}
```
Just missing the quotes.

**Comment by wickedsp1d3r** [comment]
Thank you, it is working now.
If I add quotes around the parameters, like this
```
npx node-minify --silence --compressor jsonminify --input './json/*.json' --output './json/$1.min.json'`
```
I get an error:

```
TypeError: Cannot read property 'substr' of undefined
    at createDirectory (<path>\node_modules\@node-minify\core\lib\compress.js:96:20)
    at compress (<path>\node_modules\@node-minify\core\lib\compress.js:36:3)
    at <path>\node_modules\@node-minify\core\lib\core.js:30:7
    at new Promise (<anonymous>)
    at minify (<path>\node_modules\@node-minify\core\lib\core.js:25:10)
    at <path>\node_modules\@node-minify\cli\lib\compress.js:31:23
    at new Promise (<anonymous>)
    at compress (<path>\node_modules\@node-minify\cli\lib\compress.js:30:10)
    at <path>\node_modules\@node-minify\cli\lib\cli.js:52:35
    at new Promise (<anonymous>)
```
Also, I think `--option` is not needed if the output directory is defined to the same directory as the input directory, in `--output` parameter?

**Comment by srod** [comment]
Indeed, the `--option` is not necessary.

But that's weird for the error, I tried again, it's working for me. Can you check the path for the input/output ?

Without the quotes, the $1 is not processed and I got an empty name (.min.json instead of foo.min.json)
