### ISSUE TITLE
[Version 6.1.0] Error when running CLI

### ISSUE THREAD

**Issue by linhntaim** [srod/node-minify#1211]
When running cli, I get this error:

```
C:\Users\user\AppData\Roaming\npm\node_modules\@node-minify\cli\node_modules\commander\index.js:472
      throw new Error(`option '${option.name()}' clashes with existing property '${option.attributeName()}' on Command
      ^

Error: option 'option' clashes with existing property 'option' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (C:\Users\user\AppData\Roaming\npm\node_modules\@node-minify\cli\node_modules\commander\index.js:472:13)
    at Command._optionEx (C:\Users\user\AppData\Roaming\npm\node_modules\@node-minify\cli\node_modules\commander\index.js:499:10)
    at Command.option (C:\Users\user\AppData\Roaming\npm\node_modules\@node-minify\cli\node_modules\commander\index.js:622:17)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@node-minify\cli\bin\cli.js:22:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

When I get back to version 6.0.0, it runs fine! Please check. Thanks
My Node version is v14.5.

**Comment by srvh** [comment]
Yes, I have the same error.
I am using CLI like this:

node-minify -c jsonminify -i manifest.json -o manifest2.json

And earlier it is worked correctly. But now I get the same error.
