### ISSUE TITLE
gcc fails with --use-strict

### ISSUE THREAD

**Issue by Ekliptor** [srod/node-minify#122]
node -v: v7.0.0
node-minify: v2.0.0

I use strict mode for my app:
node --use_strict app.js

But then the gcc compilation always fails.
Reproducable example

```
"use strict"; // this works, but --use-strict globally doesn't

const compressor = require('node-minify')

compressor.minify({
    compressor: 'gcc',
    input: 'foo.js',
    output: 'bar.js',
    options: {
        compilation_level: 'SIMPLE_OPTIMIZATIONS',
        language: 'ECMASCRIPT6'
    },
    buffer: 1 * 1024 * 1024,
    callback: function (err, min) {
        console.log(err)
        console.log("DONE")
    }
})
```

Results in:
```
TypeError: Cannot set property '$gwtExport' of undefined
    at /Test/node_modules/google-closure-compiler-js/jscomp.js:7410:491339
    at Object.<anonymous> (/Test/node_modules/google-closure-compiler-js/jscomp.js:7410:491399)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```

It used to work fine with --use-strict before upgrading to node-minify v2. Seem that this is not defined in that context anymore. Can you please fix this?
Thanks

**Comment by srod** [comment]
Can you first try with the java version of gcc ?

```compressor: 'gcc-legacy'```

The gcc compressor now use the new javascript version, not java version.
It will help me to figure out if this is related to it.

**Comment by Ekliptor** [comment]
Thanks for the idea. Unfortunately it's still failing with ggc-legacy.
Stacktrace:
```
/Test/node_modules/google-closure-compiler-js/jscomp.js:7410
var Wqe='object',Xqe='anonymous',Yqe='fnStack',Zqe={3:1,4:1},$qe='Unknown',_qe='\n',are='function',bre='boolean',cre='number',dre='string',ere=2147483647,fre='__java$exception',gre='__noinit__',hre={3:1,66:1},ire={3:1,73:1,66:1},jre='For input string: "',kre='null',lre=-2147483648,mre=1073741824,nre=16384,ore='\\\\',pre={3:1,4:1,6:1},qre={90:1,3:1},rre=65536,sre=55296,tre=1023,ure=65535,vre=56320,wre='\\',xre=', length: ',yre='fromIndex: ',zre=', toIndex: ',Are=', ',Bre='java.lang',Cre='Object',Dre='com.google.gwt.core.client',Ere='com.google.gwt.core.client.impl',Fre='Boolean',Gre='Number',Hre='String',Ire={3:1},Jre='com.google.common.base',Kre='use Optional.orNull() instead of Optional.or(null)',Lre='java.util',Mre={54:1},Nre='AbstractIterator',Ore={3:1,26:1,4:1},Pre={201:1,3:1,38:1,23:1},Qre='0123456789ABCDEF',Rre={141:1,60:1},Sre='0\u0660\u06F0\u07C0\u0966\u09E6\u0A66\u0AE6\u0B66\u0BE6\u0C66\u0CE6\u0D66\u0E50\u0E

TypeError: Cannot set property '$gwtExport' of undefined
    at /Test/node_modules/google-closure-compiler-js/jscomp.js:7410:491339
    at Object.<anonymous> (/Test/node_modules/google-closure-compiler-js/jscomp.js:7410:491399)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/google-closure-compiler-js/compile.js:24:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Test/node_modules/google-closure-compiler-js/index.js:25:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Test/node_modules/node-minify/lib/compressors/gcc.js:14:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Test/node_modules/node-minify/lib/compress.js:27:9)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Test/node_modules/node-minify/lib/node-minify.js:15:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Test/node_modules/node-minify/index.js:9:18)
```

**Comment by srod** [comment]
It seems that you are still using gcc not gcc-legacy
Because in the stack trace gcc.js is called instead of gcc-java.js :

``/Test/node_modules/node-minify/lib/compressors/gcc.js``

Can you try with :

```
const compressor = require('node-minify')

compressor.minify({
    compressor: 'gcc-legacy',
    input: 'foo.js',
    output: 'bar.js',
    options: {
        compilation_level: 'SIMPLE_OPTIMIZATIONS',
        language: 'ECMASCRIPT6'
    },
    buffer: 1 * 1024 * 1024,
    callback: function (err, min) {
        console.log(err)
        console.log("DONE")
    }
})
```

**Comment by srod** [comment]
Ok, my bad, I just reproduced it even with gcc-legacy.

**Comment by srod** [comment]
Can you try version 2.0.2 ?
It should be OK.

**Comment by Ekliptor** [comment]
I still get the same error about "$gwtExport" being undefined with the same code sample as above and the versions:
node -v: v7.8.0
node-minify: v2.0.4

But I switched to writing "use strict" on top of every file instead of the node argument.

**Comment by srod** [comment]
I tested with:

```js
"use strict"; // this works, but --use-strict globally doesn't

const compressor = require('node-minify')

compressor.minify({
    compressor: 'gcc',
    input: 'foo.js',
    output: 'bar.js',
    options: {
        compilation_level: 'SIMPLE_OPTIMIZATIONS',
        language: 'ECMASCRIPT6'
    },
    buffer: 1 * 1024 * 1024,
    callback: function (err, min) {
        console.log(err)
        console.log("DONE")
    }
})
```
A sample file:
```js
"use strict";

class Mangler {
  constructor(program) {
    this.program = program;
  }
}
// need this since otherwise Mangler isn't used
new Mangler();
```
And launched with `node app.js`.
But no error for now, am I missing something?

**Comment by Ekliptor** [comment]
yes when you launch it with `node app.js`  it works.
But when launching it with `node --use-strict app.js` it fails with the error above. Since v2 of node-minify some parts of the gcc compiler are no longer compatible with strict mode (as far as I can see without debugging it further).

**Comment by srod** [comment]
For now, I'm only checking for `--use_strict`, because in the first place, you were using it : `node --use_strict app.js`.
But now, you are using `node --use-strict app.js` ?
Let me know if you can stick with `use_strict`, or if you need me to add the check for `use-strict`.
