### ISSUE TITLE
How to clean console.log from js by any compressor?

### ISSUE THREAD

**Issue by hellomaya** [srod/node-minify#62]
I have googled that UglifyJS2 can clean console.log which is supported by node-minify , and I just don't get how to use these options in node-minify, I know it had options property, seems UglifyJS2 use that option property very differently..

```
var minifiedCode = uglify.minify(originalSourceCode, {
                fromString : true,
                mangle: {},
                warnings: true,
                compress:{
                    pure_funcs: [ 'console.log' ]
                }
            });
console.log(minifiedCode);
```

**Comment by srod** [comment]
You can remove all console.log with drop_console option, like that :
```javascript
new compressor.minify({
    type: 'uglifyjs',
    fileIn: 'filein.js',
    fileOut: 'fileout.js',
    options: ['--compress drop_console=true'],
    callback: function(err, min) {
    }
});
```

**Comment by hellomaya** [comment]
Worked! :+1:  Thanks a lot.

**Comment by PierBover** [comment]
The solution proposed by @srod doesn't work anymore.

```
compressor.minify({
	compressor: 'uglifyjs',
	options: ['--compress drop_console=true'],
	input: files,
	output: './build.js',
	callback: function(err, min){
		console.log("JS Build Done!");
	}
});
```

I'm using the beta `"node-minify": "^2.0.0-beta.0"`

**Comment by srod** [comment]
Can you try to pass the `options` object like that ?

```
compressor.minify({
  compressor: 'uglifyjs',
  input: 'foo.js',
  output: 'bar.js',
  options: {
    compress: true,
    drop_console: true
  },
  callback: function (err, min) {}
});
```

**Comment by PierBover** [comment]
I still get `console.log()` messages

**Comment by srod** [comment]
Ok, I will have a look.

**Comment by PierBover** [comment]
Hey @srod did you figure it out?

**Comment by srod** [comment]
It seems that we have to pass a "compress" object, according uglifyjs documentation :

```
compressor.minify({
  compressor: 'uglifyjs',
  input: 'foo.js',
  output: 'bar.js',
  options: {
    compress: {
      drop_console: true
    }
  },
  callback: function (err, min) {}
});
```

**Comment by PierBover** [comment]
Sorry for taking so long to test this.

Now I'm using:
```
compressor.minify({
	compressor: 'uglifyjs',
	input: files,
	output: './build/widgets.js',
	options: {
		compress: {
			drop_console: true
		}
	},
	callback: function(err, min){
		if(err) console.log(err);
		console.log("JS Build Done!");
	}
});
```
`files` is an array with files.

I'm getting this error:

```
JS_Parse_Error {
  message: 'Unexpected token punc «,», expected punc «:»',
  filename: 0,
  line: 1784,
  col: 6,
  pos: 45269,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)\n    at js_error (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)\n    at croak (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)\n    at token_error (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)\n    at expect_token (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2047:9)\n    at expect (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2050:36)\n    at eval (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2610:13)\n    at eval (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2073:24)\n    at expr_atom (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2540:35)\n    at maybe_unary (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)\n    at expr_ops (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2751:24)\n    at maybe_conditional (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2756:20)\n    at maybe_assign (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2780:20)\n    at expression (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2799:20)\n    at expr_list (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2565:24)\n    at subscripts (eval at <anonymous> (XXXXXX/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2699:30)' }
```

(I've obfuscated the path on my drive)

**Comment by PierBover** [comment]
It seems this is a problem with `uglify-js`. I've tried compressing directly with it and I'm getting the same error.

**Comment by PierBover** [comment]
I was a problem on my end.
