### ISSUE TITLE
npm 3.x's flat dependency structure breaks hard-coded pathing for uglifyjs, sqwish, clean-css, and csso

### ISSUE THREAD

**Issue by 3choBoomer** [srod/node-minify#66]
https://github.com/srod/node-minify/blob/master/lib/node-minify.js#L100

The hard coded paths linked above do not work with npm 3.x since it flattens out all dependencies to reduce nesting.

**Comment by srod** [comment]
Fixed in 1.3.0

**Comment by srod** [comment]
Thank you !

**Comment by NareshBanala** [comment]
I updated to 1.3.0 and now I see below error.

C:\XYZFolder\node_modules\.bin\uglifyjs:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
] killed: false, code: 8, signal: null }
ui-core compression error:  { [Error: Command failed:
C:\XYZFolder\node_modules\.bin\sqwish:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
] killed: false, code: 8, signal: null }

**Comment by srod** [comment]
I've release a beta version of v2.0.0, can you give it a try ?

```npm install node-minify@beta```

There is some small changes to do : https://github.com/srod/node-minify/blob/develop/Migrate.md
