### ISSUE TITLE
updated to 1.3.0 and getting unexpected token ILLEGAL

### ISSUE THREAD

**Issue by NareshBanala** [srod/node-minify#69]
I updated to 1.3.0 and now I see below error.

C:\XYZFolder\node_modules.bin\uglifyjs:2
basedir=dirname "$0"
^
SyntaxError: Unexpected token ILLEGAL
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
] killed: false, code: 8, signal: null }
ui-core compression error: { [Error: Command failed:
C:\XYZFolder\node_modules.bin\sqwish:2
basedir=dirname "$0"
^
SyntaxError: Unexpected token ILLEGAL
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
] killed: false, code: 8, signal: null }

**Comment by srod** [comment]
Ouch, I will try on windows env.

**Comment by srod** [comment]
Fixed in 1.3.2, can you give it a try ?

**Comment by NareshBanala** [comment]
It's working. Thank you.
