### ISSUE TITLE
Version 1.3.8 somehow broke uglifyjs compatibility

### ISSUE THREAD

**Issue by furio** [srod/node-minify#98]
Enviroment:
- EBS on Aws 
- Node 4.4.3
- Npm 2.15.1
- uglifyjs 2.7.0

What i do in one of my files is this:
```javascript
    new compressorMinify.minify({
        type: 'uglifyjs',
        options: ['--compress', '--mangle', '--screw-ie8'],
        fileIn: path.join(__dirname, 'public/a') + '/a.js',
        fileOut: path.join(__dirname, 'public/a') + '/a.min.js',
        callback: function (err, min) {
            LOG.info("Compressed a.js, error received:" + err);
        }
    });
```

What i get always is (uglifyjs not found)
```javascript
{"message":"uncaughtException: uglifyjs not found !","date":"Tue Jul 05 2016 12:43:04 GMT+0000 (UTC)","process":{"pid":3233,"uid":497,"gid":495,"cwd":"/var/app/current","execPath":"/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/node","version":"v4.4.6","argv":["/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/node","/var/app/current/bin/www.js"],"memoryUsage":{"rss":218185728,"heapTotal":120838496,"heapUsed":94357368}},"os":{"loadavg":[1.5537109375,0.5341796875,0.19384765625],"uptime":118},"trace":[{"column":17,"file":"/var/app/current/node_modules/node-minify/lib/node-minify.js","function":"getPath","line":104,"method":null,"native":false},{"column":27,"file":"/var/app/current/node_modules/node-minify/lib/node-minify.js","function":"Object.minify.fn.compress","line":132,"method":"minify.fn.compress","native":false},{"column":10,"file":"/var/app/current/node_modules/node-minify/lib/node-minify.js","function":"Object.minify","line":83,"method":"minify","native":false},{"column":5,"file":"/var/app/current/primus-setup.js","function":"generateJavascript","line":18,"method":null,"native":false},{"column":5,"file":"/var/app/current/a-setup.js","function":"module.exports","line":76,"method":"exports","native":false},{"column":29,"file":"/var/app/current/app.js","function":"","line":153,"method":null,"native":false},{"column":26,"file":"module.js","function":"Module._compile","line":409,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Object.Module._extensions..js","line":416,"method":"Module._extensions..js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":343,"method":"load","native":false},{"column":12,"file":"module.js","function":"Function.Module._load","line":300,"method":"Module._load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":353,"method":"require","native":false},{"column":17,"file":"internal/module.js","function":"require","line":12,"method":null,"native":false},{"column":78,"file":"/var/app/current/bin/www.js","function":"","line":1,"method":null,"native":false},{"column":26,"file":"module.js","function":"Module._compile","line":409,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Object.Module._extensions..js","line":416,"method":"Module._extensions..js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":343,"method":"load","native":false},{"column":12,"file":"module.js","function":"Function.Module._load","line":300,"method":"Module._load","native":false},{"column":10,"file":"module.js","function":"Function.Module.runMain","line":441,"method":"Module.runMain","native":false},{"column":18,"file":"node.js","function":"startup","line":139,"method":null,"native":false},{"column":3,"file":"node.js","function":null,"line":968,"method":null,"native":false}],"stack":["Error: uglifyjs not found !","    at getPath (/var/app/current/node_modules/node-minify/lib/node-minify.js:104:17)","    at Object.minify.fn.compress (/var/app/current/node_modules/node-minify/lib/node-minify.js:132:27)","    at Object.minify (/var/app/current/node_modules/node-minify/lib/node-minify.js:83:10)","    at generateJavascript (/var/app/current/primus-setup.js:18:5)","    at module.exports (/var/app/current/a-setup.js:76:5)","    at Object.<anonymous> (/var/app/current/app.js:153:29)","    at Module._compile (module.js:409:26)","    at Object.Module._extensions..js (module.js:416:10)","    at Module.load (module.js:343:32)","    at Function.Module._load (module.js:300:12)","    at Module.require (module.js:353:17)","    at require (internal/module.js:12:17)","    at Object.<anonymous> (/var/app/current/bin/www.js:1:78)","    at Module._compile (module.js:409:26)","    at Object.Module._extensions..js (module.js:416:10)","    at Module.load (module.js:343:32)","    at Function.Module._load (module.js:300:12)","    at Function.Module.runMain (module.js:441:10)","    at startup (node.js:139:18)","    at node.js:968:3"],"time":"2016-07-05T12:43:04.091Z","level":"error"} 
```

Reverting to 1.3.7 seems to do the trick and make everything works

**Comment by srod** [comment]
Ho gosh, I will revert uglifyjs for now.

**Comment by furio** [comment]
I don't know if it's uglifyjs or glob that broke

**Comment by srod** [comment]
Ok, so I have reverted to 1.3.7, publish in progress a new 1.3.9.

**Comment by srod** [comment]
I'm closing, it should be good with 1.3.9
